entries:
  - source: /dogu
    target: /var/www/html/warp/menu.json
    type: warp
    tag: warp
    order:
      Development Apps: 100
  - source: /services
    target: /etc/nginx/conf.d/app.conf
    type: service
    tag: webapp
    template: /etc/ces-confd/templates/app.conf.tpl
    pre-command: "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
    post-command: "/usr/sbin/nginx -s reload -c /etc/nginx/nginx.conf"
