site_name: Ecosystem Documentation
pages:
- Home: index.md
- User Guide:
  - Integration-Tests: user-guide/integration-tests.md
  - Dogu creation: user-guide/dogu-creation.md
  - Migration: user-guide/migration.md
- About: about.md
